<<<<<<< HEAD
# 5. CREATE netlify.toml in your root directory
[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  functions = "netlify/functions"

# Redirect API calls to Netlify functions
[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

# Catch-all redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/styles/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
=======
# 5. CREATE netlify.toml in your root directory
[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  functions = "netlify/functions"

# Redirect API calls to Netlify functions
[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

# Catch-all redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/styles/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
>>>>>>> 90d45b3ed162c54b2a1ed83c18e364f5ef57b94d
    Cache-Control = "public, max-age=31536000"